version: '2.0'
networks:
  yanjiang:
services:
  yanjiang-test:
    image: yz181x/yanjiang:240516-d5j
    networks:
      - yanjiang
    restart: always
    volumes:
      - ./public/scenes:/app/public/scenes
    ports:
      - "3000:3000"
